### ISSUE TITLE
ipset restore has not been implemented 

### ISSUE THREAD

**Issue by ArisAachen** [lazytiger/ipset#1]
This crate help me a lot.  
But I really think restore is an important feature since using "ipset add" may cosing to much time when we have a huge list of ip.

**Comment by ArisAachen** [comment]
useful to me, thx

**Comment by ArisAachen** [comment]
Another question, since "#![feature(c_variadic)]" is used in this crate, that means, nightly version is required   
But mostly, developer use beta or stable version instead. 
I hve found many features dont work fine in rust nightly version, so my code is no longer been compiled correctly.

**Comment by ArisAachen** [comment]
should I open a new issue if you hve any plan to solve this problem?

**Comment by lazytiger** [comment]
I have no idea how to do this unless discarding bindgen and writing some c code to wrapper it. If you have problem with nightly, maybe you should update your code, nightly is the future version rust.
