### ISSUE TITLE
rustc nightly

### ISSUE THREAD

**Issue by desdic** [lazytiger/ipset#2]
Hi,

First off, thank you for a great crate. Would it be possible to change it a bit so it does not require nightly rustc ?

Best regards
Kim

**Comment by lazytiger** [comment]
I am afraid it's not possible for now. Because I use concat_idents to generate codes that require nightly, otherwise I need a custom code generation mechanism which I don't have time for now.

**Comment by desdic** [comment]
oki thank you :)

**Comment by lazytiger** [comment]
You can use version 0.5.0 which support stable now
